### ISSUE TITLE
OP2 TODO Task List

### ISSUE THREAD

**Issue by gihanmudalige** [OP-DSL/OP2-Common#220]
Task List for OP2 Release
- [ ] Complete task list from #219
- [ ] Create OP2-APPS repo, moving generated application code - automatically regenerate code when changes to the OP2-Common repo is done. 
- [ ] Develop SPACK recipes / setup for building OP2
- [ ] Update/replace OP2 code generator with new code generator (use Clang/Libtooling for parsing and elemental kernel  -  transformations, Jinja2/Marco templates for target code generation) - see work in https://github.com/jdjfisher/op-cg
- [ ] OP2 - CI flow with tests @ Warwick systems (including testing OP2-Hydra against OP2 library)
- [ ] Add to code generator to generate new parallelizations - SYCL and HIP (merge work from SYCL and HIP branches)

**Comment by gihanmudalige** [comment]
- [ ] (minor task) create a develop branch, make it default and update READ me with a "how to contribute" section as in https://github.com/OP-DSL/OPS/blob/develop/README.md
- [ ] Create a readthedocs setup for documentation and move / rewrite the PDF docs in there (similar to what we have done now for OPS)

**Comment by gihanmudalige** [comment]
@bozbez , may be the 3rd and 4th is now done ?

**Comment by bozbez** [comment]
Yes, but I'll wait until the Spack maintainers have reviewed and merged the Spack PR before checking that off.

**Comment by ZamanLantra** [comment]
**op_exit issue with JIT**
Root Cause : KernelInfo() correctly joins threads, but it's called after the CUDA context is torn down by op_exit(), leaving NVRTC with a destroyed context.
**Workaround** : force sequential (blocking) using OP_JIT_SEQ_COMPILE=1
**Fix** : in your solver code, ensure all JIT threads are joined before op_exit() is called. Wait on jit_active_threads == 0 before that point.

#0  0x0000155548a3f854 in __sigsetjmp () from /lib64/libc.so.6
#1  0x000015554cd0c224 in ?? () from /home/local/Nvidia-hpc-sdk/2025_253//Linux_x86_64/25.3/cuda/lib64/libnvrtc.so.12
#2  0x000015554cce0f36 in ?? () from /home/local/Nvidia-hpc-sdk/2025_253//Linux_x86_64/25.3/cuda/lib64/libnvrtc.so.12
#3  0x000015554ccd8525 in ?? () from /home/local/Nvidia-hpc-sdk/2025_253//Linux_x86_64/25.3/cuda/lib64/libnvrtc.so.12
#4  0x00001555496ce351 in ?? () from /home/local/Nvidia-hpc-sdk/2025_253//Linux_x86_64/25.3/cuda/lib64/libnvrtc.so.12
#5  0x0000155549a206ca in nvrtcCompileProgram () from /home/local/Nvidia-hpc-sdk/2025_253//Linux_x86_64/25.3/cuda/lib64/libnvrtc.so.12
#6  0x00000000004134e8 in op::f2c::KernelInfo::compile(unsigned long)::{lambda(auto:1, auto:2)#1}::operator()<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long) const (jit_src=..., __closure=0x128c500, hash=13679853920966426665)
    at /home/home/do017/dc-lant2/work/OP2-Common/op2/include/op_f2c_helpers.h:411
#7  std::__invoke_impl<void, op::f2c::KernelInfo::compile(unsigned long)::{lambda(auto:1, auto:2)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>(std::__invoke_other, op::f2c::KernelInfo::compile(unsigned long)::{lambda(auto:1, auto:2)#1}&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, unsigned long&&) (__f=...)
    at /home/local/gcc/14.1.0/include/c++/14.1.0/bits/invoke.h:61
#8  std::__invoke<op::f2c::KernelInfo::compile(unsigned long)::{lambda(auto:1, auto:2)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long>(op::f2c::KernelInfo::compile(unsigned long)::{lambda(auto:1, auto:2)#1}&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, unsigned long&&) (__fn=...) at /home/local/gcc/14.1.0/include/c++/14.1.0/bits/invoke.h:96
#9  std::thread::_Invoker<std::tuple<op::f2c::KernelInfo::compile(unsigned long)::{lambda(auto:1, auto:2)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x128c4d8)
    at /home/local/gcc/14.1.0/include/c++/14.1.0/bits/std_thread.h:292
#10 std::thread::_Invoker<std::tuple<op::f2c::KernelInfo::compile(unsigned long)::{lambda(auto:1, auto:2)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> >::operator()() (this=0x128c4d8)
    at /home/local/gcc/14.1.0/include/c++/14.1.0/bits/std_thread.h:299
#11 std::thread::_State_impl<std::thread::_Invoker<std::tuple<op::f2c::KernelInfo::compile(unsigned long)::{lambda(auto:1, auto:2)#1}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> > >::_M_run() (this=0x128c4d0)
    at /home/local/gcc/14.1.0/include/c++/14.1.0/bits/std_thread.h:244
#12 0x0000155548f352b4 in std::execute_native_thread_routine (__p=0x128c4d0) at ../../../../../libstdc++-v3/src/c++11/thread.cc:104
#13 0x0000155548a8b3f9 in start_thread () from /lib64/libc.so.6
#14 0x0000155548b105d0 in clone3 () from /lib64/libc.so.6
